# Generated by Django 3.2.5 on 2021-07-23 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_house_profiles', '0003_auto_20210722_1715'),
        ('rent_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='profile',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='rent_a_house_profiles.profile'),
            preserve_default=False,
        ),
    ]
