# Generated by Django 3.2.5 on 2021-07-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0002_offer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='profile',
        ),
    ]
