# Generated by Django 3.2.5 on 2021-07-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0005_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
