# Generated by Django 3.2.5 on 2021-08-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0008_auto_20210813_1426'),
        ('rent_app', '0009_alter_offer_image'),
    ]

    operations = [
    ]
