# Generated by Django 3.2.5 on 2021-08-13 11:41

from django.db import migrations, models
import rent_a_house.rent_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('rent_app', '0010_merge_0008_auto_20210813_1426_0009_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='offers', validators=[rent_a_house.rent_app.validators.validate_image_format]),
        ),
    ]
