# Generated by Django 3.2.5 on 2021-07-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_house_auth', '0002_rentahouseuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentahouseuser',
            name='first_name',
            field=models.CharField(default='Gosho', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentahouseuser',
            name='last_name',
            field=models.CharField(default='Goshov', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentahouseuser',
            name='phone_number',
            field=models.IntegerField(default=3123031),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentahouseuser',
            name='profile_image',
            field=models.ImageField(default=2, upload_to='profile_images'),
            preserve_default=False,
        ),
    ]
