# Generated by Django 3.2.5 on 2021-07-21 11:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_house_auth', '0003_auto_20210721_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentahouseuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, null=True, region='BG'),
        ),
    ]
