# Generated by Django 3.2.5 on 2021-07-21 11:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_house_auth', '0004_alter_rentahouseuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentahouseuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, null=True, region='BG'),
        ),
        migrations.AlterField(
            model_name='rentahouseuser',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
