# Generated by Django 3.2.5 on 2021-07-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_house_auth', '0005_auto_20210721_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentahouseuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='rentahouseuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='rentahouseuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='rentahouseuser',
            name='profile_image',
        ),
    ]
