# Generated by Django 3.2.5 on 2021-07-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_house_auth', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
