# Generated by Django 3.2.5 on 2021-07-22 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent_a_house_auth', '0009_profile_is_complete'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
